
name: code-plan
on: { pull_request: { paths: ['code/**'] } }
jobs:
  tf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with: { terraform_version: 1.6.6 }
      - run: terraform -chdir=code/main init
      - run: terraform -chdir=code/main plan
